wp-cli - Allow localized installation with existing `l10n` data dir
Before: Suppose you are trying to install with existing source code. If you specify `--lang`, it will complain
that `--langtarfile=...` is required (even if the language files already exist).

After: You can install a language using *either* `--langtarfile=...` *or* an existing l10n file.

Comment: If you try to install with a language that you don't have, then it will still complain, ie:

```
Error: Failed to find data for language (fr_US). Please download valid language data with --langtarfile=<path/to/tarfile>.
```